Q6 adds getComments & fetchComments
rubyrubyruby02/be-project-API-NC-news pull request #6
Opened 2023-08-15 14:23 UTC by rubyrubyruby02

2023-08-15 14:44 UTC, EddTheDuck requested changes
Need to add an extra test but the rest looks great :)

2023-08-15 14:44 UTC, EddTheDuck commented on __tests__/integration.tests.js
> +            response.body.comments.forEach((comment)=> {
If asserting inside a forEach you should also check the length of the array

2023-08-15 14:44 UTC, EddTheDuck commented on __tests__/integration.tests.js
> +    })
What would happen when given a valid ID but there are no comments? ie. returns an empty array.

Are you satisfied that your code would handle this situation correctly?

2023-08-16 07:53 UTC, mezzDavies approved these changes
Looks good you are welcome to merge. I have left one comment for your consideration - have a play around/refactor as I feel there is a bit of extraneous code 😄

2023-08-16 07:53 UTC, mezzDavies commented on controllers/comments.controller.js
> +    if(article_id){
Would there be a case when there wasn't an article_id? 🤔 

This controller has been invoked due to the matching url which has an article_id (valid or not) included. I'm pretty certain you can do away with this logic - refactor and see if it your test still passes. The beauty of tests! 👍

2023-08-16 08:13 UTC, merged